In [1]:
import numpy as np
from qibo import models, hamiltonians

# Create XXZ Hamiltonian for six qubits
hamiltonian = hamiltonians.XXZ(6)
# Create QAOA model
qaoa = models.QAOA(hamiltonian)

# Optimize starting from a random guess for the variational parameters
initial_parameters = 0.01 * np.random.uniform(0,1,4)
best_energy, final_parameters, extra = qaoa.minimize(initial_parameters, method="BFGS")

[Qibo 0.2.21|INFO|2025-10-15 10:47:12]: Using qibojit (numba) backend on /CPU:0


In [2]:
best_energy, final_parameters, extra 

(np.float64(3.4843735486539646),
 array([0.41518376, 2.10033345, 0.4756647 , 3.63927783]),
   message: Optimization terminated successfully.
   success: True
    status: 0
       fun: 3.4843735486539646
         x: [ 4.152e-01  2.100e+00  4.757e-01  3.639e+00]
       nit: 18
       jac: [-4.441e-06 -4.470e-06  6.020e-06  2.682e-07]
  hess_inv: [[ 8.515e-02  9.424e-03 -3.494e-02 -3.539e-02]
             [ 9.424e-03  1.262e-01  6.418e-02  2.017e-02]
             [-3.494e-02  6.418e-02  1.066e-01  4.866e-02]
             [-3.539e-02  2.017e-02  4.866e-02  1.069e-01]]
      nfev: 140
      njev: 28)